package spreadsheet;
import javax.swing.table.AbstractTableModel;

public class ClientTableModel extends AbstractTableModel {        
    
    private static final long serialVersionUID = 1L; //generated by VSCode
    public static final int numberOfCells = 9;

    @Override
    public boolean isCellEditable(int rowIndex, int columnIndex){
        return true;
    }
        
    //The event is fired when the use accesses a cell by clicking it or by pressing tab based on its column index
    @Override
    public Object getValueAt(int row, int col) {
        return Driver.client.con.getValue(String.valueOf(col)) != null ? Driver.client.con.getValue(String.valueOf(col)) : "";
    }

    //The event is fired when the use types into the cell and presses Enter,Tab or shits its focus away
    @Override    
    public void setValueAt(Object aValue, int rowIndex, int columnIndex) {          
        Driver.client.con.setValue(String.valueOf(columnIndex), String.valueOf(aValue)); 
        fireTableCellUpdated(rowIndex, columnIndex);       
    }
    
    @Override
    public int getRowCount() {        
        return 1;
    }
    
    @Override
    public int getColumnCount() {        
        return numberOfCells;
    }
}